name: deployment_aml
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6
- nb_conda
- tornado
- cudatoolkit==9.0
- tensorflow-gpu==1.10.0
- urllib3
- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - papermill
  - python-dotenv
  - Pillow
  - wget==3.2
  - matplotlib
  - toolz
  - tqdm
  - azure-cli
  - keras==2.2.0
  - azureml-sdk[notebooks, contrib]
  - locustio
